-- Learning provider
INSERT [Valid].[LearningProvider] ([UKPRN]) VALUES (54867248)

--Learner
INSERT [Valid].[Learner] ( [LearnRefNumber], [PrevLearnRefNumber], [PrevUKPRN], [ULN], [FamilyName], [GivenNames], [DateOfBirth], [Ethnicity], [Sex], [LLDDHealthProb], [NINumber], [PriorAttain], [Accom], [ALSCost], [PlanLearnHours], [PlanEEPHours], [MathGrade], [EngGrade], [HomePostcode], [CurrentPostcode], [LrnFAM_DLA], [LrnFAM_ECF], [LrnFAM_EDF1], [LrnFAM_EDF2], [LrnFAM_EHC], [LrnFAM_FME], [LrnFAM_HNS], [LrnFAM_LDA], [LrnFAM_LSR1], [LrnFAM_LSR2], [LrnFAM_LSR3], [LrnFAM_LSR4], [LrnFAM_MCF], [LrnFAM_NLM1], [LrnFAM_NLM2], [LrnFAM_PPE1], [LrnFAM_PPE2], [LrnFAM_SEN], [ProvSpecMon_A], [ProvSpecMon_B]) VALUES ( N'4556474573', NULL, NULL, 4556474573, N'FamilyName', N'GivenNames', CAST(N'1988-10-23' AS Date), 98, N'F', 2, N'AB123456C', 1, NULL, NULL, NULL, NULL, NULL, NULL, N'OX17 1EZ', N'OX17 1EZ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

--LearningDelivery
INSERT [Valid].[LearningDelivery] ([LearnRefNumber], [LearnAimRef], [AimType], [AimSeqNumber], [LearnStartDate], [OrigLearnStartDate], [LearnPlanEndDate], [FundModel], [ProgType], [FworkCode], [PwayCode], [StdCode], [PartnerUKPRN], [DelLocPostCode], [AddHours], [PriorLearnFundAdj], [OtherFundAdj], [ConRefNumber], [EmpOutcome], [CompStatus], [LearnActEndDate], [WithdrawReason], [Outcome], [AchDate], [OutGrade], [SWSupAimId], [LrnDelFAM_ADL], [LrnDelFAM_ASL], [LrnDelFAM_EEF], [LrnDelFAM_FFI], [LrnDelFAM_FLN], [LrnDelFAM_HEM1], [LrnDelFAM_HEM2], [LrnDelFAM_HEM3], [LrnDelFAM_HHS1], [LrnDelFAM_HHS2], [LrnDelFAM_LDM1], [LrnDelFAM_LDM2], [LrnDelFAM_LDM3], [LrnDelFAM_LDM4], [LrnDelFAM_NSA], [LrnDelFAM_POD], [LrnDelFAM_RES], [LrnDelFAM_SOF], [LrnDelFAM_SPP], [LrnDelFAM_WPP], [ProvSpecMon_A], [ProvSpecMon_B], [ProvSpecMon_C], [ProvSpecMon_D]) VALUES ( N'4556474573', N'ZPROG001', 1, 1, CAST(N'2017-09-01' AS Date), NULL, CAST(N'2018-09-08' AS Date), 36, 25, NULL, NULL, 98765, NULL, N'OX17 1EZ', NULL, NULL, NULL, NULL, NULL, 6, CAST(N'2017-10-30' AS Date), NULL, 8, NULL, NULL, N'83282eb2aa2230439a9964374c163b9c', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'105', NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [Valid].[LearningDelivery] ( [LearnRefNumber], [LearnAimRef], [AimType], [AimSeqNumber], [LearnStartDate], [OrigLearnStartDate], [LearnPlanEndDate], [FundModel], [ProgType], [FworkCode], [PwayCode], [StdCode], [PartnerUKPRN], [DelLocPostCode], [AddHours], [PriorLearnFundAdj], [OtherFundAdj], [ConRefNumber], [EmpOutcome], [CompStatus], [LearnActEndDate], [WithdrawReason], [Outcome], [AchDate], [OutGrade], [SWSupAimId], [LrnDelFAM_ADL], [LrnDelFAM_ASL], [LrnDelFAM_EEF], [LrnDelFAM_FFI], [LrnDelFAM_FLN], [LrnDelFAM_HEM1], [LrnDelFAM_HEM2], [LrnDelFAM_HEM3], [LrnDelFAM_HHS1], [LrnDelFAM_HHS2], [LrnDelFAM_LDM1], [LrnDelFAM_LDM2], [LrnDelFAM_LDM3], [LrnDelFAM_LDM4], [LrnDelFAM_NSA], [LrnDelFAM_POD], [LrnDelFAM_RES], [LrnDelFAM_SOF], [LrnDelFAM_SPP], [LrnDelFAM_WPP], [ProvSpecMon_A], [ProvSpecMon_B], [ProvSpecMon_C], [ProvSpecMon_D]) VALUES ( N'4556474573', N'ZPROG001', 1, 2, CAST(N'2018-01-03' AS Date), NULL, CAST(N'2018-11-30' AS Date), 36, 25, NULL, NULL, 98765, NULL, N'OX17 1EZ', NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, N'83282eb2aa2230439a9964374c163b9c', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'105', NULL, NULL, NULL, NULL, NULL, NULL)

--TrailblazerApprenticeshipFinancialRecord
INSERT [Valid].[TrailblazerApprenticeshipFinancialRecord] ( [LearnRefNumber], [AimSeqNumber], [TBFinType], [TBFinCode], [TBFinDate], [TBFinAmount]) VALUES ( N'4556474573', 1, N'TNP', 1, CAST(N'2017-09-01' AS Date), 12000)
INSERT [Valid].[TrailblazerApprenticeshipFinancialRecord] ( [LearnRefNumber], [AimSeqNumber], [TBFinType], [TBFinCode], [TBFinDate], [TBFinAmount]) VALUES ( N'4556474573', 1, N'TNP', 2, CAST(N'2017-09-01' AS Date), 3000)
INSERT [Valid].[TrailblazerApprenticeshipFinancialRecord] ( [LearnRefNumber], [AimSeqNumber], [TBFinType], [TBFinCode], [TBFinDate], [TBFinAmount]) VALUES ( N'4556474573', 2, N'TNP', 1, CAST(N'2018-01-03' AS Date), 12000)
INSERT [Valid].[TrailblazerApprenticeshipFinancialRecord] ( [LearnRefNumber], [AimSeqNumber], [TBFinType], [TBFinCode], [TBFinDate], [TBFinAmount]) VALUES ( N'4556474573', 2, N'TNP', 2, CAST(N'2018-01-03' AS Date), 3000)
